// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcqeooamsixczemkrkzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjcWVvb2Ftc2l4Y3plbWtya3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzQ1MTYsImV4cCI6MjA3MTMxMDUxNn0.mex0Khei9d04quznmxhE_YJw7z4JYzs7wh5OdJ8qJig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});